{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from Acquire.Client import User"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "user = User(\"chryswoods\", identity_url=\"http://35.187.209.158:8080/t/identity\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "(url,qrcode) = user.request_login()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZoAAAGaAQAAAAAefbjOAAADAElEQVR4nO2cwY3bMBBF30QC9kgDLmBLoTtISakpHUilpAPyuACFnwNJrZTNJXFgb6TxyaD9YAoac+b/GdvEHz/mL3/OgEMOOeSQQw45dEzI2mOE2cwgj9iNxZjNzG65v+H2lO059HgoSpJSW7RbeDNNeYRY1wZJkvbQ47bn0OOh3A4A+yZJU36R3UKB+bXFQT1BnrU9hx4GjR9W8rVAKIh8FfHHWP7NJzn0f0AfImK+YCJfIE4FI7yZyM/ankNPg4KkCSCmQcAgTSzW8gcgqfwKPW57Dj0ams3M7NIW7QbYLb/IviUAlio1nrU9hx6dNXZW9mIQSns2v74ZhL3X/cmvyaF7IKqq3IjM3TMp7dckafrk1+TQPVCLiHooBElTKGgKbU1TLTBabVF9C4+II0O07/1aT642VU8dazAkPyPOAK1ZYxBRhRYbm2BgPSh6+HhEHBnqN7nKzUH17itRne1mb9fEIs8aJ4C2ZwSh1EZGKyZ2SURTKHhEHB9q6nN+LUB+kRHKWHufMV2x+H0owLJTqZ/8mhy6B1pd7GXU/DUB+SoDEBlEXqx2OMgv3vs8AbTJGu9pQtJWeNaE4XXEOaB+RtQiYTHiJAwGWXWtQsJiQkbuJvZnvyaH7oG2WqMJzzYQsdGhsduarj6PD/WbHLQKz6GZ2nFnZuIu9smgxYg/zOrkVDWws1n1paba/Xrz3ucJoN7XYFg9qEKblFjPiGpgJ+9rnAHqWmMNixYRg94Fx6YF5lnj8NAaEavc7HZlKyZ6w8M7XSeB9vMR9BCo9gT9jABqbeERcXiod8PXhlbs0qO9mtioT68jjg9Vh6qLiKGIfC0W0zJCSHXN6sQ+3tc4EVSb3gnMLtASRh55F6NP3Z5Dz6kjYho2YxAb/QFsxyU8axwZ+vibLkDkC5ptKLUfGiew+ZI8a5wA+k1ELKPmGxghYYRlrD/xuveTHPo/oI1DVSfxp90L2+a49zVOAa0uNrDO378bVttWqNyPOANk/s9kDjnkkEMOOeTQX0I/AVBSsDirT0bXAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<qrcode.image.pil.PilImage at 0x106747668>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qrcode"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "http://35.187.209.158:8080/t/identity/s?id=1c072fe0\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<a href='http://35.187.209.158:8080/t/identity/s?id=1c072fe0'>Login here</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from IPython.core.display import HTML\n",
    "print(url)\n",
    "HTML(\"<a href='%s'>Login here</a>\" % url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "ename": "RemoteFunctionCallError",
     "evalue": "Error calling 'get_status' at 'http://35.187.209.158:8080/t/identity'. Server returned error code '-1' with message 'Error <class 'get_status.InvalidSessionError'>: Cannot find the session '1c072fe0-a2cd-493e-8f04-ae20b92cbddd''",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRemoteFunctionCallError\u001b[0m                   Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-0feb82ef0f19>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0muser\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_login\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/Work/acquire/source/Acquire/Client/_user.py\u001b[0m in \u001b[0;36mwait_for_login\u001b[0;34m(self, timeout, polling_delta)\u001b[0m\n\u001b[1;32m    517\u001b[0m             \u001b[0;31m# block forever....\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    518\u001b[0m             \u001b[0;32mwhile\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 519\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_poll_session_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    520\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    521\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_logged_in\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Work/acquire/source/Acquire/Client/_user.py\u001b[0m in \u001b[0;36m_poll_session_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    472\u001b[0m         result = _call_function(identity_url, \"get_status\",\n\u001b[1;32m    473\u001b[0m                                 \u001b[0musername\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_username\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 474\u001b[0;31m                                 session_uid=self._session_uid)\n\u001b[0m\u001b[1;32m    475\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    476\u001b[0m         \u001b[0;31m# look for status = 0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Work/acquire/source/Acquire/Service/_function.py\u001b[0m in \u001b[0;36mcall_function\u001b[0;34m(service_url, function, args_key, response_key, public_cert, args, **kwargs)\u001b[0m\n\u001b[1;32m    290\u001b[0m                 \u001b[0;34m\"Error calling '%s' at '%s'. Server returned \"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    291\u001b[0m                 \u001b[0;34m\"error code '%d' with message '%s'\"\u001b[0m \u001b[0;34m%\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 292\u001b[0;31m                 (function, service_url, result[\"status\"], result[\"message\"]))\n\u001b[0m\u001b[1;32m    293\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    294\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRemoteFunctionCallError\u001b[0m: Error calling 'get_status' at 'http://35.187.209.158:8080/t/identity'. Server returned error code '-1' with message 'Error <class 'get_status.InvalidSessionError'>: Cannot find the session '1c072fe0-a2cd-493e-8f04-ae20b92cbddd''"
     ]
    }
   ],
   "source": [
    "user.wait_for_login()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "user.is_logged_in()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "user.logout()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
